table 'Dim Salesperson'
	lineageTag: 711c7c00-7de0-478d-8c21-4f5026e61e06

	column 'Salesperson Key'
		dataType: int64
		formatString: 0
		lineageTag: 8139e128-bd2e-4ad1-ba5b-6c6a4b3f3087
		summarizeBy: none
		sourceColumn: salesperson_key

		annotation SummarizationSetBy = Automatic

	column Entity
		dataType: string
		lineageTag: 4b169a1f-f2f7-4c28-8bf6-7cd0e5458504
		summarizeBy: none
		sourceColumn: entity

		annotation SummarizationSetBy = Automatic

	column 'SLP Code'
		dataType: int64
		formatString: 0
		lineageTag: e626ffcf-070a-4de4-b6d2-f9798bd2d8a4
		summarizeBy: none
		sourceColumn: slp_code

		annotation SummarizationSetBy = Automatic

	column 'SLP Name'
		dataType: string
		lineageTag: 5036a783-b3ca-4b76-9654-8acc6bcf0066
		summarizeBy: none
		sourceColumn: slp_name

		annotation SummarizationSetBy = Automatic

	column 'Display Name'
		dataType: string
		lineageTag: fa1de4a4-c922-4e41-b8b8-db03463acac9
		summarizeBy: none
		sourceColumn: display_name

		annotation SummarizationSetBy = Automatic

	column 'Market Group'
		dataType: string
		lineageTag: 4aff9e7a-617e-4616-8f0c-d47fc5deddf0
		summarizeBy: none
		sourceColumn: market_group

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: b64c54ea-3de6-4f77-b5ec-4ca2bd1b25c1
		summarizeBy: none
		sourceColumn: region

		annotation SummarizationSetBy = Automatic

	column 'Is Active'
		dataType: string
		lineageTag: 8f2297ab-c82f-4e37-a447-3c85b23a112f
		summarizeBy: none
		sourceColumn: is_active

		annotation SummarizationSetBy = Automatic

	column sub_region
		dataType: string
		lineageTag: 8921cfda-78bc-4696-bf0d-1c47cb8d10d3
		summarizeBy: none
		sourceColumn: sub_region

		annotation SummarizationSetBy = Automatic

	column sub_region_count
		dataType: int64
		formatString: 0
		lineageTag: 81c57b16-361c-432e-80bf-fceb869f0199
		summarizeBy: none
		sourceColumn: sub_region_count

		annotation SummarizationSetBy = Automatic

	partition dim_salesperson = m
		mode: import
		source =
				let
				    Source = AzureStorage.DataLake("https://stqmssaledatalakeprod.dfs.core.windows.net/"),
				    #"Filtered Rows" = Table.SelectRows(Source, each ([Folder Path] = "https://stqmssaledatalakeprod.dfs.core.windows.net/bronze/gold/")),
				    #"https://stqmssaledatalakeprod dfs core windows net/bronze/gold/_dim_salesperson parquet" = #"Filtered Rows"{[#"Folder Path"="https://stqmssaledatalakeprod.dfs.core.windows.net/bronze/gold/",Name="dim_salesperson.parquet"]}[Content],
				    #"Imported Parquet" = Parquet.Document(#"https://stqmssaledatalakeprod dfs core windows net/bronze/gold/_dim_salesperson parquet")
				in
				    #"Imported Parquet"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

